name: cid_explorer
description: Web App for exploring and debugging S5 CIDs
version: 0.2.0
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  convert: ^3.0.1
  filesize:
    git: https://github.com/redsolver/filesize.git
  http: ^1.2.1
  timeago: ^3.6.1
  mime: ^1.0.5
  s5: ^0.2.0
  js: ^0.6.7

dev_dependencies:
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  lints: ^3.0.0